#!/usr/bin/env bash

if (( $# != 2 )); then
  echo 'usage: '$(basename $0)' <input>.yaml field '
  exit 0
fi

cat > kustomization.yaml <<KUSTOMIZATION
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kam
configMapGenerator:
- name: jupyterhub
  files:
  - jupyterhub_config.py
generatorOptions:
 disableNameSuffixHash: true
 annotations:
   openshift.io/generated-by: OpenShiftNewApp
 labels:
   app: jupyterhub
resources:
KUSTOMIZATION

let length=$(cat $1 | yq r - -P $2 | yq r - -P --length)
let length=$length-1
for i in $(seq 0 $length); do
  kind=$(cat $1 | eval "yq r - -P $2[$i].kind")
  name=$(cat $1 | eval "yq r - -P $2[$i].metadata.name")
  kind=$(echo $kind | sed 's/\([a-z]\)\([A-Z]\)/\1-\2/g' | sed 's/\([A-Z]\{2,\}\)\([A-Z]\)/\1-\2/g' | tr '[:upper:]' '[:lower:]')
  if [[ $kind == "config-map" ]]; then
    continue
  fi
  name=$(eval "echo $name")
  cat $1 | eval "yq r - -P $2[$i]" > ${kind}-${name}.yaml
  echo '- '${kind}-${name}.yaml >> kustomization.yaml
done
