apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: intel-python-notebook
  name: intel-python-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: intel-python-notebook:latest
  source:
    git:
      uri: https://github.com/preethivenkatesh/notebooks
      ref: main
    contextDir: idp
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
  - type: ConfigChange
