apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with intel-tensorflow"
    opendatahub.io/notebook-image-name: "Intel Tensorflow Notebook Image"
    opendatahub.io/notebook-image-url: "https://github.com/preethivenkatesh/notebooks"
  labels:
    opendatahub.io/notebook-image: "true"
  name: intel-python-notebook
  namespace: preethi-intel-tf
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/kamkasravi/tensorflow-notebook
    from:
      kind: DockerImage
      name: quay.io/preethi_venk7/intel-python-notebook:latest
    name: latest
